### ISSUE TITLE
Clarify globbing implementation

### ISSUE THREAD

**Issue by dheiman** [broadinstitute/wdl#108]
As the definition of globbing can vary from shell to shell, and language to language, the WDL spec should really clearly define its version of globbing rather than just giving examples.

Obviously, there is the most basic implementation of `*`, `?`, `[...]`, though the only examples given are of `*`.

However, as this seems to be the only form of pattern matching available in WDL, the addition of [brace expansion](https://en.wikipedia.org/wiki/Bash_(Unix_shell)#Brace_expansion), [character classes, and bash-style extended globbing](https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html) would be excellent.

**Comment by katevoss** [comment]
Thanks for your input, I'll move this over to our documentation repo to make sure this gets into the Spec document.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/dsde-docs #2061](https://github.com/broadinstitute/dsde-docs/issues/2061) via [**ZenHub**](https://www.zenhub.com/)
