### ISSUE TITLE
Revamp `object`

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/wdl#109]
**Needs Refinement**

We want to be able to define types for the values of objects. One suggestion was something like the following (note `struct` is using as a possible replacement for `object`, see below):

    struct MyType {
      o_f: File
      x: Array[String]
    }

    MyType foo = read_object(...)

It will coerce to the types it expects and if it can't that's a failure.

Open questions:

- Do we make a new construct (e.g. `struct` above), or replace objects
- If replace, who (if anyone) is currently using `object`
- What's the right syntax, regardless of the name of the construct. This needs focus grouping.

**Comment by katevoss** [comment]
Issue moved to [broadinstitute/cromwell #2283](https://github.com/broadinstitute/cromwell/issues/2283) via [**ZenHub**](https://www.zenhub.com/)
