### ISSUE TITLE
Syntax Highlighter doesn't like Optional Inputs

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/wdl#33]
I just used the attached wdl file (saved as .txt so github would attach it) in IntelliJ and the highlighter seems to find an error with the first '?' in the file. The error pops up as: <postfix quantifier>, WdlTokenType.IDENTIFIER or WdlTokenType.LSQUARE expected, for '?'

Any subsequent '?' don't have an error.

[OptionalInput.wdl.txt](https://github.com/broadinstitute/wdl/files/188116/OptionalInput.wdl.txt)
![screen shot 2016-03-24 at 11 20 01 am 2](https://cloud.githubusercontent.com/assets/13020550/14021748/3b6f2fee-f1b3-11e5-9512-4c89715911ce.png)

**Comment by vdauwera** [comment]
This no longer reproduces in my hand but reopen if I'm wrong
