### ISSUE TITLE
Getting started documentation out of date with regard to "inputs" command

### ISSUE THREAD

**Issue by mbookman** [broadinstitute/wdl#34]
I am following the instructions here:

https://github.com/broadinstitute/wdl#getting-started-with-wdl

I have downloaded cromwell-0.19.jar.
I created the example "hello.wdl".

The README indicates that there is an "inputs" command to see the inputs to the wdl.
When I run "java -jar cromwell.jar", it indicates that there are just two commands "run" and "server".
It appears that the "inputs" command has moved to "wdltool".

I downloaded wdltool from https://github.com/broadinstitute/wdltool/releases

```
$ java -jar wdltool.jar inputs hello.wdl
{
  "test.hello.name": "String"
}

```
The documentation should be updated:

1. To direct the user to download wdltool.jar
1. To show use of "wdltool.jar inputs" command.

Also at the bottom of this first example, it indicates:

> Since the hello task returns a File, the result is a file that contains the string "hello world!" in it.

It would be worth adding a demonstration of that:

```
$ cat /home/user/test/c1d15098-bb57-4a0e-bc52-3a8887f7b439/call-hello/stdout8818073565713629828.tmp
hello world!

```

**Comment by geoffjentry** [comment]
Closed by #35
