### ISSUE TITLE
Add tutorial scripts to scripts/tutorials

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/wdl#39]
The tutorial scripts featured on the website should be mirrored here. They can live in `scripts/tutorials/` (`scripts/` will be created by https://github.com/broadinstitute/wdl/pull/36 when it's merged).

**Comment by knoblett** [comment]
This includes all of [these](https://software.broadinstitute.org/wdl/userguide/topic?name=wdl-scripts) scripts, correct? Are there any additional scripts that should be added?

Additionally, sorry this fell through the cracks--I was clearing my inbox today and found this issue. By the way, is there a way to view all issues assigned to you, regardless of repository?

**Comment by vdauwera** [comment]
Yes, correct.

No worries :) Yes, through the zenhub board you can set which repos you want to look at, and which person's assignments.

**Comment by vdauwera** [comment]
(done in #46)
