### ISSUE TITLE
Links to standard library documentation are broken in the top-level README

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/wdl#40]

**Comment by vdauwera** [comment]
Can you clarify which links you mean? All the links in README.md are working for me.

**Comment by LeeTL1220** [comment]
https://github.com/broadinstitute/wdl/blob/wdl2/SPEC.md#standard-library  

did not work for me...  This is what was in the README

**Comment by vdauwera** [comment]
Got it, in https://github.com/broadinstitute/wdl/pull/41 

Anything else to edit while we're at it?

**Comment by LeeTL1220** [comment]
That was all I saw
