### ISSUE TITLE
Update WDL tutorials with new files & URL links

### ISSUE THREAD

**Issue by knoblett** [broadinstitute/wdl#49]
- moving my files to /wdl
- adding a URL to the comments in the header of my files that points to the tutorial they are linked to

**Comment by vdauwera** [comment]
While you're at it, could you please also address https://github.com/broadinstitute/dsde-docs/issues/1153? Thanks!

**Comment by sooheelee** [comment]
Ok, I uploaded a WDL and JSON set and created two pull-requests related to these uploads. 

Before I upload the other sets, is it possible to have these as one pull-request? If I can help it, I don't want to create more review work for folks.

**Comment by sooheelee** [comment]
I have answered my own question. I need to clone master and create my own branch.

**Comment by sooheelee** [comment]
@vdauwera Who can give me permission to push?

**Comment by knoblett** [comment]
Did you handle setting up the folders for tour own files then? I thought I would be handling uploading your files as a part of my pull request, but I can take it off my list if you would rather do it yourself.

**Comment by sooheelee** [comment]
I gotta learn Kate. I'll be uploading regularly and can't be bugging you each time. Maybe modify your list to "Help teach Soo Hee upload and put in a pull request"?

**Comment by knoblett** [comment]
Absolutely fine; it's not terribly difficult once you get the hang of what commands to enter when. I can send you my step-by-step process if you'd like, or I can teach you in person when you are ready to merge.

**Comment by sooheelee** [comment]
I think I have the basics down. Might be asking questions later on.

**Comment by knoblett** [comment]
No problem!

Closing this issue now, as I forgot that I had it associated with the PR that is now merged.
