### ISSUE TITLE
wdl bwa parameters

### ISSUE THREAD

**Issue by mcgml** [broadinstitute/wdl#62]
Hi

Thanks for releasing this WDL script. I noticed the bwa parameters are: `bwa_commandline="bwa mem -K 100000000 -p -v 3 -t 16 $bash_ref_fasta"`

What is the `-K` flag for? it is not defined in the bwa manual. Also is `-M` missing?

Thanks
Matt

**Comment by vdauwera** [comment]
Hi @mcgml, apologies for the late reply. I don't know the answer to this but will consult the team.

@sooheelee, do you happen to know about this -K parameter? I'm not finding any reference to it anywhere either. If you don't, can you please ask Heng at office hours tomorrow?

**Comment by vdauwera** [comment]
For this type of question, please ask in the WDL forum at https://gatkforums.broadinstitute.org/wdl
