### ISSUE TITLE
Update PublicPairedSingleSampleWf options.json to include other us-central1 zones

### ISSUE THREAD

**Issue by mbookman** [broadinstitute/wdl#64]
[PublicPairedSingleSampleWf_160927.options.json](https://github.com/broadinstitute/wdl/blob/develop/scripts/broad_pipelines/PublicPairedSingleSampleWf_160927.options.json) only includes 2 of the 4 `us-central1` zones:

```
    "zones": "us-central1-b us-central1-c"
```

I'm not sure if there is a rational for limiting the zones that Cromwell can use to run tasks. The 4 [Compute Engine zones](https://cloud.google.com/compute/docs/regions-zones/regions-zones) in `us-central1` are:
- us-central1-a
- us-central1-c
- us-central1-b
- us-central1-f

**Comment by vdauwera** [comment]
I'm not aware of any rationale, but we should check with the Cromwell team just in case. @knoblett, could you please ask red team?

**Comment by ruchim** [comment]
Hey all, Cromwell doesn't restrict the usage of any particular zones.

**Comment by sooheelee** [comment]
When you specify multiple zones, then how is a zone picked for running processes?

**Comment by mbookman** [comment]
The zone is selected by the Pipelines API at random from the list.

**Comment by sooheelee** [comment]
Does this reduce the probability of preemption if using preemptible instances?

**Comment by mbookman** [comment]
That is the expectation.

**Comment by sooheelee** [comment]
Great. Thanks for clarifying.

**Comment by vdauwera** [comment]
I believe this was done
