### ISSUE TITLE
Need to update the sing-samp wf doc

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/wdl#65]
See https://github.com/broadinstitute/wdl/blob/develop/scripts/broad_pipelines/PublicPairedSingleSampleWf_160927.md

The timestamp was incremented to follow the newest version but the doc wasn't actually updated. Changes are minimal but should be noted, and the supported versions should be updated.

**Comment by sooheelee** [comment]
Is this something you will do?

**Comment by vdauwera** [comment]
this was done
