### ISSUE TITLE
GATK wrappers should use workaround for optional arrays

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/wdl#70]
Until #25 is fixed, the [gatk wrappers](https://github.com/broadinstitute/wdl/tree/28d4997/scripts/wrappers/gatk) should not be using optional arrays, such as the intervals files. Instead they should use [this bash workaround](https://github.com/broadinstitute/wdl/issues/25#issuecomment-192277430), with something similar to:

```
Array[String]? foo

command {
  if [ -n '${sep=',' foo}' ]; then
    FLAG=--prefix=${sep=',' foo}
  else
    FLAG=''
  fi

  echo $FLAG
}
```

**Comment by vdauwera** [comment]
So we never got around to fixing the GATK wrappers... do we still need to or is this handled in Cromwell 24?

**Comment by vdauwera** [comment]
This was fixed iirc
