### ISSUE TITLE
Feature request: Nested scatter loops

### ISSUE THREAD

**Issue by awacs** [broadinstitute/wdl#71]
Please add the ability to do nested scatter loops. The current single sample workflow runs HaplotypeCaller in parallel by scattering over interval. I would like to add a scattering by sample step so it can handle multiple samples.

**Comment by vdauwera** [comment]
We have a ticket to implement "workflows of workflows", which will effectively provide the functionality you need.

**Comment by awacs** [comment]
I've tried to implement this with sub_workflows but I'm still having trouble. 
Example:
inputTSV.txt
###
a\tb
c\td
####
doublesplit.wdl
###
import "null.wdl" as other
workflow doublesplit{
  File inputSamplesFile
  Array[Array[String]] inputFiles = read_tsv(inputSamplesFile)
  scatter (inputstring in inputFiles){
      call other.nullscatter{input: inputLine=inputstring}

  }
}
##
null.wdl
###
workflow nullscatter{
	Array[String] FileList=inputLine
    # String inputLine
	# Array[Array[String]] FileList=read_tsv(inputLine)
    scatter (FileName in FileList){
        call nulltask {input: Name=FileName}
    }

}
task nulltask{
    String Name
    command {echo ${Name}}
    output {String N="${Name}"}
}
######
The stdout is attached here

[test.txt](https://github.com/broadinstitute/wdl/files/650461/test.txt)

**Comment by vdauwera** [comment]
This can now be achieved by using subworkflows (aka workflow imports). We will document this in the user guide soon; in the meantime see the WDL spec for details.
