### ISSUE TITLE
Data for running Broad Pipelines

### ISSUE THREAD

**Issue by anton-khodak** [broadinstitute/wdl#92]
I would like to run `PublicPairedSingleSampleWf_160927` workflow, but I can not find where to look for the sample data in the [`input.json`](https://github.com/broadinstitute/wdl/blob/develop/scripts/broad_pipelines/PublicPairedSingleSampleWf_160927.inputs.json). Could it be mentioned in the README?

**Comment by vdauwera** [comment]
Ok, we'll clarify in the README. In the meantime, FYI the data is in a google bucket called "genomics-public-data". The "gs://genomics-public-data/" part is a unique address on Google Cloud Storage (GCS), which you should be able to find through the google cloud console. Let me know if you have trouble finding that.

**Comment by anton-khodak** [comment]
@vdauwera Thank you for clarification, another reason I am asking is because I am getting the following error while running the workflow
```[2017-02-18 11:25:11,21] [error] BackgroundConfigAsyncJobExecutionActor [01577930PairedEndSingleSampleWorkflow.CreateSequenceGroupingTSV:NA:1]: Error attempting to Execute
cromwell.backend.sfs.SharedFileSystem$$anonfun$localizeInputs$1$$anon$1: Failures during localization:
java.lang.IllegalArgumentException: Could not find suitable filesystem among Default to parse gs://genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.dict.
```

I am running it without the [config file](https://github.com/broadinstitute/wdl/blob/develop/scripts/broad_pipelines/PublicPairedSingleSampleWf_160927.options.json), with it I have another error:
```
Unsupported key/value pair in WorkflowOptions: defaultRuntimeOptions -> {"zones":"us-central1-b us-central1-c"}
```

Should I somehow mention the filesystem in the config file? 
I would ask it on the GATK forum, but for some reasons I can not log in.

**Comment by vdauwera** [comment]
@anton-khodak FYI we prefer to answer these kinds of questions in the WDL forum [here](http://gatkforums.broadinstitute.org/wdl).
